name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo install cargo-fuzz
    - run: cargo fuzz build --sanitizer none --dev

  build:
    strategy:
      matrix:
        features: ["", "parse", "stringify", "parse stringify"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test --verbose --features "${{ matrix.features }}"

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: cargo build --verbose -p souper-ir-tests
    - run: cargo test --verbose -p souper-ir-tests

  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo install cargo-readme
    - run: cargo readme -t .README.tpl > README.md
    - run: |
        git diff --exit-code || {
            echo
            echo "============================================================"
            echo
            echo "README.md is not up to date! Run"
            echo
            echo "    $ cargo readme -t .README.tpl > README.md"
            echo
            echo "to update it."
            exit 1
        }
